### ISSUE TITLE
Host plugin in jenkinsci organization?

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/bootstraped-multi-test-results-report-plugin#108]
Hey,

Is there any reason this plugin isn't hosted with the rest of plugins in the [jenkinsci](http://github.com/jenkinsci) GitHub organization?
When anyone searches for changes, they normally only look for the jenkinsci organization, plus publishing documentation to the plugin site is only supported from the jenkinsci org.

https://www.jenkins.io/doc/developer/publishing/requesting-hosting/

@BogdanLivadariu

**Comment by BogdanLivadariu** [comment]
no reason at all,
usually I forgot to do this :)

**Comment by NotMyFault** [comment]
No worries, thanks for the swift response. Would you be interested in hosting the plugin from the jenkinsci org?
That would be beneficial for the reasons mentioned above.

**Comment by BogdanLivadariu** [comment]
I’ll try to look over link you provided next week to see how to transfer
the repo

Would you be interested getting write access to it ?!
My time for oss is quite limited atm.

thanks

**Comment by NotMyFault** [comment]
I can assist you with the transfer, for sure. If it helps you, don't hesitate to add me to this repository, and I'll initiate the transfer and get you settled :)

**Comment by NotMyFault** [comment]
> I’ll try to look over link you provided next week to see how to transfer the repo

Sounds great. The docs don't cover that, but I invited you to the `jenkinsci-transfer` organization.

You should be able to [transfer this repository](https://github.com/web-innovate/bootstraped-multi-test-results-report/transfer) to the dedicated transfer organization.

**Comment by BogdanLivadariu** [comment]
@NotMyFault  I've just transfered the repo here: https://github.com/jenkinsci-transfer/bootstraped-multi-test-results-report
